name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pillow python3-numpy python3-pip mesa-utils libgl1-mesa-dri libglapi-mesa libosmesa6 python3-setuptools
        sudo pip3 install --ignore-installed selenium requests
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-chromedriver: true
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Build
      run: |
        python3 ${{ github.workspace }}/utils/build/build.py
    - name: Test
      run: |
        xvfb-run -a python3 ${{ github.workspace }}/tests/run_tests.py
